# Generated by Django 3.2.8 on 2021-11-07 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 11, 35, 34, 971609, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_key',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
