# Generated by Django 3.2.8 on 2021-11-07 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211107_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 11, 38, 23, 712866, tzinfo=utc)),
        ),
    ]
