# Generated by Django 3.2.8 on 2021-11-12 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211111_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 18, 32, 54, 292729, tzinfo=utc)),
        ),
    ]
