# Generated by Django 2.2.16 on 2020-11-05 13:14

from django.db import migrations, transaction


def forward_func(apps, schema_editor):
    try:
        from authnapp.models import ShopUser, ShopUserProfile

        with transaction.atomic():
            users = ShopUser.objects.all()
            for user in users:
                ShopUserProfile.objects.create(user=user)
    except Exception as exp:
        print(f"Cann't create user profile: {exp}")


def reverse_func(apps, schema_editor):
    try:
        from authnapp.models import ShopUserProfile

        with transaction.atomic():
            ShopUserProfile.objects.all().delete()
    except Exception as exp:
        print(f"Cann't delete users profiles: {exp}")


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0004_user_profile"),
    ]

    operations = [migrations.RunPython(forward_func, reverse_func)]
