# Generated by Django 2.2.16 on 2020-11-16 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20201116_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 12, 59, 59, 301884, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
